
name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Setup permission
      run: chmod u+x ./gradlew
    
    - name: Build with Gradle Wrapper 1
      run: ./gradlew cleanBuild idea remapSpigotJar --no-daemon -i --stacktrace --refresh-dependencies

    - name: Build with Gradle Wrapper 2
      run: ./gradlew build --no-daemon -i --stacktrace

    - name: Build with Gradle Wrapper 3
      run: ./gradlew build collect --no-daemon -i --stacktrace

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/libs
